GO
/****** Lukas 18923798379 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE STORE (
 		STORE_ID  nvarchar(100) NOT NULL,
		ID int NOT NULL,
		STORENAME nvarchar(50) DEFAULT NULL,
		STOREDISTRICT nvarchar(200) DEFAULT NULL,
		STOREADDRESS nvarchar(500) DEFAULT NULL,
		CREATEDATE nvarchar(19) DEFAULT NULL,
		LASTDATE nvarchar(19) DEFAULT NULL,
		STORESTATUSID int NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[STORE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
